grim.data1 <- read.csv("final_project_data.csv" , header = TRUE)
prop.table(table(grim.data1$bike.share))
prop.table(table(grim.data1$messaging))
library (psych)
describe(grim.data1$miles)
grim.data1$environcons_avg <- rowMeans (grim.data1[, c("environmental.commitment_1", "environmental.commitment_2", "environmental.commitment_3", "environmental.commitment_4", "environmental.commitment_5", "environmental.commitment_6", "environmental.commitment_7", "environmental.commitment_8", "environmental.commitment_9", "environmental.commitment_10")])
library (psych)
describe(grim.data1$environcons_avg)
prop.table(table(grim.data1$source))
prop.table(table(grim.data1$gender))
prop.table(table(grim.data1$race))           
describe(grim.data1$age)
cor(grim.data1[, c("miles", "environcons_avg", "age")], use = "pairwise.complete.obs")
library (apaTables)
apa.1way.table(source,  miles, data = grim.data1)
library (effsize)
cohen.d(grim.data1$miles, grim.data1$source, na.rm = TRUE )
t.test(grim.data1$miles ~ grim.data1$source, var.equal = TRUE)
apa.2way.table(bike.share, messaging, miles, data = grim.data1) 
summary(aov(grim.data1$miles ~ grim.data1$bike.share + grim.data1$messaging + grim.data1$bike.share*grim.data1$messaging))
library (DescTools)
ScheffeTest(aov(grim.data1$miles ~ grim.data1$bike.share + grim.data1$messaging + grim.data1$bike.share*grim.data1$messaging))
27495/(176679 + 27495)
4150/(176679 + 4150)
109/(176679 + 109)
alpha(grim.data1[, c ("environmental.commitment_1", "environmental.commitment_2", "environmental.commitment_3", "environmental.commitment_4", "environmental.commitment_5", "environmental.commitment_6", "environmental.commitment_7", "environmental.commitment_8", "environmental.commitment_9", "environmental.commitment_10")])
summary(lm(grim.data1$miles ~ grim.data1$environcons_avg))
plot(grim.data1$miles ~ grim.data1$environcons_avg)
abline(lm(grim.data1$miles ~ grim.data1$environcons_avg))
apa.1way.table(bike.share,  miles, data = grim.data1)
apa.1way.table(messaging,  miles, data = grim.data1)
interaction.plot(grim.data1$bike.share, grim.data1$messaging, grim.data1$miles, ylim = c(86, 236), xlab = "Enrollment Condition", trace.label = "Messaging Condition", ylab = "Miles biked")
